config/routes.rb
QuestoesVf::Application.routes.draw do
  resources :comentarios, :only => [:new, :create, :destroy]
  
  root :to => 'home#index', :as => 'inicial'

  resources :provas, :except => [:index] 
  match 'provas/:id/pre_do' => 'provas#pre_do', :via => :get, :as => 'pre_do_test' ## |
  match 'provas/:id/do/:estudante_id' => 'provas#index', :via => [:post, :get], :as => 'do_test'         ## | INICIAR PROVA -> FAZER PROVA -> ENVIAR PROVA
  match 'provas/:id/do' => 'provas#do', :via => :post, :as => 'submit_do_test'                   ## |

  match 'estudantes/:estudante_id' => 'estudantes#index', :as => 'index_estudantes'

  match 'professores/:professor_id' => 'professors#index', :as => 'index_professores'

  match 'relatorios' => 'relatorios#index', :via => :get
  match 'relatorios' => 'relatorios#report', :via => :post, :as => 'report'
  match 'relatorios/texto' => 'relatorios#texto', :via => :post
  match 'relatorios/excel' => 'relatorios#excel', :via => :post

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/:provider', :to => 'sessions#create', as: :create_session

end

app/models/prova.rb
class Prova < ActiveRecord::Base
    validates :titulo, :presence => true
    validates :disponivel_data_inicio, :presence => true
    validates :disponivel_data_fim, :presence => true
    validates :duracao, :presence => true

    has_many :questaos
    has_many :alunos_provas

    accepts_nested_attributes_for :questaos, allow_destroy: true

    scope :da_disciplina, lambda { |disciplina| where("provas.disciplina_id = ?", disciplina) }
    scope :do_professor_disciplina, lambda { |id, disciplina| where("professor_id = ? and disciplina_id = ?", id, disciplina) }
    scope :disponiveis, lambda { where("disponivel_data_inicio <= ? and disponivel_data_fim > ?", DateTime.now, DateTime.now) }

    # Filtros Grid
    scope :excluir_antigas, lambda { where("disponivel_data_inicio > ?",  180.days.ago) }
    scope :excluir_resolvidas, lambda { where('alunos_provas.data_inicio is null').joins("LEFT OUTER JOIN alunos_provas ON provas.id = alunos_provas.provas_id") }

    def get_nota(aluno_id, disciplina)
        nota = nil
        nota_valor = 0
        valor_prova = 0

        aluno_prova = AlunosProvas.where('provas_id = ? and alunos_id = ?', self.id, aluno_id).first

        if aluno_prova != nil && aluno_prova.data_inicio != nil && self.disciplina_id.to_s() == disciplina.to_s()
            questoes = Questao.where("prova_id = ?", self.id)

            questoes.each { |questao|
                erradas = 0

                valor_prova = valor_prova + questao.valor

                proposicoes = Proposicao.where("questao_id = ?", questao.id)

                valor_prop = questao.valor / proposicoes.count

                proposicoes.each { |proposicao|
                    resposta = Resposta.where("proposicao_id = ? and aluno_id = ?", proposicao.id, aluno_id).first

                    if resposta != nil && resposta.resposta != proposicao.resposta
                        erradas += 1
                        nota = nota_valor;
                    end

                    if resposta != nil && resposta.resposta == proposicao.resposta
                        nota_valor = nota_valor + valor_prop
                        nota = nota_valor
                    end
                    
                    if erradas == self.qtd_falsa_para_anular && self.qtd_falsa_para_anular > 0
                        nota_valor = nota_valor - (valor_prop * self.qtd_verdadeira_anula)
                        nota = nota_valor
                        erradas = 0
                    end
                }

                if nota && nota < 0
                    nota = 0
                    nota_valor = 0
                end
            }
        end

        # Normaliza a nota do estudante para ficar entre 0 e 10
        if nota != nil
            nota = (nota / valor_prova) * 10.0
        end

        return nota
	end

    def get_data_inicio(aluno_id)
        aluno_prova = AlunosProvas.where('provas_id = ? and alunos_id = ?', self.id, aluno_id).first

        return aluno_prova != nil ? aluno_prova.data_inicio : nil
    end

    def get_data_fim(aluno_id)
        aluno_prova = AlunosProvas.where('provas_id = ? and alunos_id = ?', self.id, aluno_id).first

        return aluno_prova != nil ? aluno_prova.data_fim : nil
    end

	def get_media(disciplina_id)
        media = nil
        valor_media = 0.0

        num = 1;

        if !is_avaliable && !is_editable
    	   alunos_provas = AlunosProvas.where('provas_id = ? and data_inicio is not null', self.id)

           num = alunos_provas.count

           alunos_provas.each { |aluno_prova|
                nota = get_nota(aluno_prova.alunos_id, disciplina_id)
                valor_media = valor_media + nota ||= 0.0
                media = valor_media
           }
        end

        if media != nil
            media = media / num
        end

        return media
	end

    # Segundos para fim da prova
    def get_end_time(aluno_id)
        tempo = DateTime.now.to_i()

        data_inicio = self.get_data_inicio(aluno_id)

        if data_inicio != nil
            tempo = data_inicio.to_i() + self.duracao * 60
        end

        return tempo
    end

    def is_editable
        return self.disponivel_data_inicio > DateTime.now
    end

    def is_avaliable
        return self.disponivel_data_inicio <= DateTime.now && self.disponivel_data_fim > DateTime.now 
    end

    def times_over(aluno_id)
        return self.get_end_time(aluno_id) <= DateTime.now.to_i() || self.get_data_fim(aluno_id) != nil
    end

    def end_time(aluno_id)
        retorno = false

        aluno_prova = AlunosProvas.where('provas_id = ? and alunos_id = ?', self.id, aluno_id).first

        if aluno_id != nil
            aluno_prova.data_fim = DateTime.now
            retorno = aluno_prova.save
        end

        return retorno
    end
end

app/controllers/provas_controller.rb
# encoding: utf-8
class ProvasController < ApplicationController
	def index
		@prova = Prova.find(params[:id])

		# Checa se a prova já foi feita
		if @prova.get_data_inicio(params[:estudante_id]) != nil	&& @prova.times_over(params[:estudante_id])
			redirect_to prova_path(@prova, :disciplina => params[:disciplina])
		else
			aluno_prova = AlunosProvas.where('provas_id = ? and alunos_id = ?', @prova.id, params[:estudante_id]).first
			data_inicio = @prova.get_data_inicio(params[:estudante_id])

			change = false

			if aluno_prova != nil && data_inicio == nil
				aluno_prova.data_inicio = DateTime.now
				change = true
			elsif aluno_prova == nil
				aluno_prova = AlunosProvas.new(:alunos_id => params[:estudante_id], :provas_id => @prova.id, :data_inicio => DateTime.now)	
				change = true
			end
		
			if change && !aluno_prova.save
				redirect_to pre_do_test_path(@prova, :disciplina => params[:disciplina])
			end
		end
	end

	# Verifica se a prova já foi feita se foi redireciona para tela show
	def pre_do
		@prova = Prova.find(params[:id])
		if params[:estudante_id] == nil
			params[:estudante_id] = params[:redu_user_id]
		else
			params[:redu_user_id] = params[:estudante_id]
		end

		params[:estudante_id] = params[:redu_user_id]

		if @prova.get_data_inicio(params[:redu_user_id]) != nil && @prova.times_over(params[:redu_user_id])
			redirect_to prova_path(@prova, :disciplina => params[:disciplina], :estudante_id => params[:redu_user_id])
		end

		if !@prova.times_over(params[:redu_user_id])
			redirect_to do_test_path(@prova, :disciplina => params[:disciplina], :estudante_id => params[:redu_user_id])
		end
	end

	def do
		ok = true

		@prova = Prova.find(params[:prova_id])

		#if !@prova.times_over(params[:estudante_id])
			Resposta.transaction do
				params[:respostas].each { |resposta| 
					resposta_obj = Resposta.new(resposta)

					if resposta_obj.resposta == nil
						resposta_obj.resposta = false
					end

					if !resposta_obj.save
						ok = false
					end
				}
			end
		#end

		if ok
			@prova.end_time(params[:estudante_id])
			redirect_to index_estudantes_path(params[:estudante_id], {:disciplina => params[:disciplina]})
		else
			render :do
		end
	end

	def new # GET
		@prova = Prova.new
	end

	def create
		@prova = Prova.new(params[:prova])
		@prova.disponivel_data_fim = @prova.disponivel_data_fim + 23.hours + 59.minutes

		if @prova.save
			# Cria o canvas da prova
			client = client(params[:prova][:disciplina_id])
			subject = client.create_subject("Prova - " + @prova.titulo)
			client.create_lecture(subject.body['id'], @prova.titulo, QuestoesVf::Application.config.root_url + pre_do_test_path(@prova.id, :disciplina => params[:prova][:disciplina_id]))

			redirect_to index_professores_path(params[:prova][:professor_id], :disciplina => params[:prova][:disciplina_id])
		else
			render :new
		end
	end

	def show # ver resultado da prova
		@prova = Prova.find(params[:id])
	end

	def edit
		@prova = Prova.find(params[:id])

		if !@prova.is_editable()
			redirect_to index_professores_path(params[:professor_id], {:disciplina => params[:disciplina]})
		end
	end

	def update
		@prova = Prova.find(params[:id])

	    if @prova.is_editable() && @prova.update_attributes(params[:prova])
	      redirect_to index_professores_path(params[:prova][:professor_id], :disciplina => params[:prova][:disciplina_id])
	    else
	      render :edit
    	end
	end

	def destroy
	end
end

app/helpers/prova_helper.rb
module ProvaHelper
end

app/views/provas/_comentarios.html.erb
<div class="novo_comentario">
	<%= form_tag comentarios_path do %>
		<input type="hidden" value="<%= params[:id] %>" name="prova_id" />
		<input type="hidden" value="<%= params[:disciplina] %>" name="disciplina" />
		<input type="hidden" value="<%= params[:estudante_id] %>" name="estudante_id" />
		<input type="hidden" value="<%= params[:professor_id] %>" name="professor_id" />

		<input type="hidden" value="<%= params[:estudante_id] %>" name="comentario[aluno_id]" />
		<input type="hidden" value="<%= questao_id %>" name="comentario[questao_id]" />
		<div class="control-group control-inline">
			<div class="control-label">
			    <label for="comentario_texto">Comentário</label>
		  	</div>
		  	<div class="controls">
			    <textarea maxlength="200" id="comentario_texto" name="comentario[texto]"></textarea>
			</div>
			<div class="controls">
				<input type="submit" value="Comentar" name="comentar" class="button-default" />
			</div>
		</div>
	<% end %>
</div>

<table>
	<thead>
		<tr>
			<th style="width: 20%">Nome</th>
			<th style="width: 50%">Comentário</th>
			<th style="width: 25%">Tempo</th>
			<th style="width: 5%">Ranking</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% comentarios.each do |comentario| %>
		<tr>
			<td><%= comentario.get_nome %></td>
			<td>
				<%= comentario.texto %>
			</td>
			<td>
				<%= comentario.pretty_date %>
			</td>
			<td><%= comentario.ranking == nil ? 0.0 : comentario.ranking %></td>
			<td>
				<% if comentario.aluno_id.to_s() == params[:estudante_id] %>
				<%= button_to("X", comentario_path(comentario, :prova_id => params[:id], :disciplina => params[:disciplina], :estudante_id => params[:estudante_id]), {:title => "Remover comentário", :method => :delete}) %>
				<% else %>
					
				<% end %>
			</td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/provas/_form.html.erb
<%= form_for @prova, :html => { :class => "form-horizontal" } do |f| %>
	<input type="hidden" name="prova[disciplina_id]" value="<%= params[:disciplina] %>" />
	<input type="hidden" name="prova[professor_id]" value="<%= params[:professor_id] %>" />
	<div id="passo1" data-background-position="0">
		<% if @prova.errors.any? %>
	    <div class="error_messages">
	      <h2><%= pluralize(@prova.errors.count, "error") %> prohibited this prova from being saved:</h2>
	      <ul>
	      <% @prova.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

		<div class="control-group row">
			<div class="control-label span2">
				<%= f.label :disponivel_data_inicio, 'Disponível de' %>
				<span class="required" title="Campo obrigatório" rel="tooltip">*</span>
			</div>
			<div class="controls span4" style="width: 88px">
				<%= f.text_field :disponivel_data_inicio, { :readonly => "", :value => @prova.disponivel_data_inicio ? @prova.disponivel_data_inicio.strftime("%d/%m/%Y") : "" } %>
			</div>
			<div class="control-label" style="margin-left: 13px">
				<%= f.label :disponivel_data_fim, 'até' %>
			</div>
			<div class="controls span4" style="width: 88px; margin-left:13px">
				<%= f.text_field :disponivel_data_fim, { :readonly => "", :value => @prova.disponivel_data_fim ? @prova.disponivel_data_fim.strftime("%d/%m/%Y") : "" } %>
			</div>
		</div>

		<div class="control-group row">
			<div class="control-label span2">
				<%= f.label :titulo %>
				<span class="required" title="Campo obrigatório" rel="tooltip">*</span>
			</div>
			<div class="controls span4">
				<%= f.text_field :titulo, {:placeholder => "Digite o título da prova", :maxlength => 30} %>
			</div>
		</div>

		<div class="control-group row">
			<div class="control-label span2">
				<%= f.label :cabecalho, 'Cabeçalho' %>
			</div>
			<div class="controls span4">
				<%= f.text_field :cabecalho, :placeholder => "Digite o cabeçalho da prova" %>
			</div>
		</div>

		<div class="control-group row">
			<div class="control-label span2">
				<%= f.label :rodape, 'Rodapé' %>
			</div>
			<div class="controls span4">
				<%= f.text_field :rodape, :placeholder => "Digite o rodapé da prova" %>
			</div>
		</div>

		<div class="control-group row" style="margin-left: 25px">
			<div class="controls span4" style="width: 50px">
				<%= f.text_field :qtd_verdadeira_anula %>
			</div>
			<div class="control-label" style="margin-left: 17px">
				<span>
					alternativas erradas anulam
				</span>
			</div>
			<div class="controls span4" style="width: 50px">
				<%= f.text_field :qtd_falsa_para_anular %>
			</div>
			<div class="control-label" style="margin-left: 17px">
				<span>
					alternativas corretas
				</span>
			</div>
		</div>

		<div class="control-group row">
			<div class="control-label span2">
				<%= f.label :duracao, 'Duração' %>
				<span class="required" title="Campo obrigatório" rel="tooltip">*</span>
			</div>
			<div class="controls span4">
				<%= f.text_field :duracao, { :placeholder => "Duração máxima da prova", :maxlength => 3 } %>
			</div>
		</div>

		<div class="control-group row">
			<div class="control-label span2">
				<label>Justificativas</label>
			</div>
			<div class="controls span4">
				<%= f.label :justificar_falsa, :class => "control-checkbox" do %>
					<%= f.check_box :justificar_falsa %>
					Justificar Erradas
				<% end %>
				<%= f.label :justificar_verdadeira, :class => "control-checkbox" do %>
					<%= f.check_box :justificar_verdadeira %>
					Justificar Corretas
				<% end %>
			</div>
		</div>
	</div>

	<div id="passo2" data-background-position="-22">
		<div class="add_questao" style="float:right;margin-right:20px;margin-bottom:20px">
			<%= link_to_add_fields "Adicionar Questão", f, :questaos %>
		</div>
		<ul class="questoes" style="clear:both">
			<%= f.fields_for :questaos do |builder| %>
				<%= render 'questao_campos', f: builder %>
			<% end %>
		</ul>
	</div>

	<div id="passo3" data-background-position="-44">
		<h3>Geral</h3>
		<br />
		<label><strong>Título</strong> <span class="titulo_res"></span></label><br />
		<label><strong>Cabeçalho</strong> <span class="cabecalho_res"></span></label><br />
		<label><strong>Rodapé</strong> <span class="rodape_res"></span></label><br />
		<label><span class="anula_errada_res"></span><strong> alternativas erradas anulam</strong> <span class="anula_correta_res">2</span><strong> alternativas corretas</strong></label><br />
		<label><strong>Disponível de </strong> <span class="disponivel_inicio_res"></span> <strong>a </strong><span class="disponivel_fim_res"></span></label><br />
		<label><strong>Duração</strong> <span class="duracao_res"></span><strong> mim</strong></label><br />
		<label><strong>Justificar Errada</strong> <span class="justificar_errada_res"></span></label><br />
		<label><strong>Justificar Correta</strong> <span class="justificar_correta_res"></span></label><br />
		<br />
		<h3>Questões</h3>
		<br />
		<input type="hidden" value='<li><span><div class="control-group control-inline"><div class="controls"><label class="control-radio" style="width:90px">#CHECK#</label></div><div class="control-label" style="margin: 1px 20px"><label>#ENUNCIADO_PROPOSICAO#</label></div></div></span></li>' class="proposicao_res" />
		<input type="hidden" value='<li><span class="titulo_questao">Questão</span><ul><li><span>#ENUNCIADO_QUESTAO#<strong> (vale #VALOR# pontos)</strong></span></li>#PROPOSICAO#</ul></li>' class="questao_res" />
		<ul class="questoes_res">
			<!--<li>
				<span>Questão</span>
				<ul>
					<li>
						<span>#ENUNCIADO_QUESTAO# <strong> (#VALOR#)</strong></span>
					</li>
					<li>
						<span>
							<div class="control-group control-inline">
								<div class="controls">
									<label class="control-radio" style="width:15px">
										<input type="radio" value="true" disabled #CHECK_V# />
										V
									</label>
									<label class="control-radio" style="width:15px">
										<input type="radio" value="false" disabled #CHECK_F# />
										F
									</label>
								</div>
								<div class="control-label" style="margin: 5px 20px">
									<label>#ENUNCIADO_PROPOSICAO#</label>
								</div>
							</div>
						</span>
					</li>
				</ul>
			</li>-->
		</ul>
	</div>
<% end %>

app/views/provas/_proposicao.html.erb
<div class="proposicao">
	<input type="hidden" name="proposicao_id" value="<%= proposicao.id %>" />
	<div class="control-group control-inline">
	  	<div class="controls">
		    <label class="control-radio">
		    	<input type="radio" value="true" class="resposta_<%= proposicao_counter + 1 %>" name="<%= proposicao.id %>" />
		    </label>
		    <label class="control-radio">
		    	<input type="radio" value="false" class="resposta_<%= proposicao_counter + 1 %>" name="<%= proposicao.id %>" />
		    </label>
		    <span class="proposicao_enunciado">
		    	<%= proposicao.texto %>
		    </span>
		</div>
	</div>
</div>

app/views/provas/_proposicao_campos.html.erb
<li class="proposicao_li">
	<span>
		<div class="control-group control-inline">
		  	<div class="controls">
			    <label class="control-radio" style="width:15px">
			    	<%= f.radio_button :resposta, "true" %>
			      	V
			    </label>
			    <label class="control-radio" style="width:15px">
			    	<%= f.radio_button :resposta, "false" %>
			    	F
			    </label>
			</div>
			<div class="control-label" style="margin: 5px 20px">
			    <%= f.label :texto, "Enunciado" %>
			    <span class="required" title="Campo obrigatório" rel="tooltip">*</span>
			</div>
			<div class="controls" style="margin-top:5px">
				<%= f.text_field :texto, { :placeholder => "Enunciado da proposição", :style => "width:356px" } %>
			</div>
			<div class="remove_icon remove_proposicao"></div>
		</div>
	</span>
</li>

app/views/provas/_proposicao_respondida.html.erb
<div class="proposicao">
	<input type="hidden" name="proposicao_id" value="<%= proposicao.id %>" />
	<div class="control-group control-inline">
	  	<div class="controls">
		    <label class="control-radio">
		    	<input type="radio" value="true" disabled class="resposta" <%= resposta ? 'checked="checked"' : "" %> name="<%= proposicao.id %>" />
		    </label>
		    <label class="control-radio">
		    	<input type="radio" value="false" disabled class="resposta" <%= resposta ? "" : 'checked="checked"' %> name="<%= proposicao.id %>" />
		    </label>
		    <span class="proposicao_enunciado">
		    	<%= proposicao.texto %>
		    </span>
		</div>
	</div>
</div>

app/views/provas/_prova_info.html.erb
<span class="tempo_prova">
	<span class="tempo_total">
		<strong>Tempo total disponível:</strong>
		<%= duracao %> mim
	</span>
	<br />
	<span class="tempo_restante">
		<strong>Tempo restante:</strong>
		<span id="time_left" data-time="<%= tempo_restante %>"></span>
	</span>
</span>
<span class="data_prova">
	<strong>Data início:</strong> <%= disponivel_inicio.strftime('%d/%m/%Y %H:%M') %><br />
	<strong>Data fim:</strong> <%= disponivel_fim.strftime('%d/%m/%Y %H:%M') %>
</span>

app/views/provas/_questao_campos.html.erb
<li class="questao_li">
	<span class="titulo_questao">Questão 1</span>
	<div class="remove_icon remove_questao"></div>
	<ul>
		<li>
			<span>
				<div class="control-group control-inline" style="margin-bottom:5px">
				  <div class="control-label" style="margin-right:50px">
				    <%= f.label :valor, "Valor" %>
				    <span class="required" title="Campo obrigatório" rel="tooltip">*</span>
				  </div>
				  <div class="controls">
				    <%= f.text_field :valor, { :placeholder => "Pontos da questão", :style => "width:150px" } %>
				    <%= link_to_add_fields "Adicionar Proposição", f, :proposicaos %>
				  </div>
				</div>
			</span>
		</li>
		<li>
			<span>
				<div class="control-group control-inline">
				  <div class="control-label" style="margin-right:20px">
				    <%= f.label :enunciado, "Enunciado" %>
				    <span class="required" title="Campo obrigatório" rel="tooltip">*</span>
				  </div>
				  <div class="controls">
				  	<%= f.text_area :enunciado, { :placeholder => "Enunciado da questão", :style => "width:450px; height:70px; max-height:70px" } %>
				  </div>
				</div>
			</span>
		</li>
		<%= f.fields_for :proposicaos do |builder| %>
			<%= render "proposicao_campos", f: builder %>
		<% end %>
	</ul>
</li>

app/views/provas/do.html.erb
<% content_for :header do %>
  <%= render "shared/estudante_header" %>
<% end %>

<% if @resposta.errors.any? %>
<div class="error_messages">
  <h2><%= pluralize(@resposta.errors.count, "error") %> prohibited this prova from being saved:</h2>
  <ul>
  <% @resposta.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/provas/edit.html.erb
<% content_for :header do %>
  <%= render "shared/professor_header" %>
<% end %>

<div id="form_steps">
	<nav>
		<ul>
			<li></li>
			<li></li>
			<li></li>
		</ul>
		<ul id="steps_titles">
			<li><a href="#">Geral</a></li>
			<li class="navMeio"><a href="#">Questões</a></li>
			<li><a href="#">Resumo</a></li>
		</ul>
	</nav>
</div>

<fieldset id="form_container">
	<%= render 'form' %>
</fieldset>
<div id="nav_buttons">
	<a href="#" data-next-step="#passo1" class="button-default prev-button">Voltar</a>
	<a href="#" data-next-step="#passo2" class="button-default next-button">Continuar</a>
	<a href="#" class="button-success submit-button">Atualizar</a>
</div>

app/views/provas/index.html.erb
<% content_for :header do %>
  <%= render "shared/estudante_header" %>
<% end %>

<fieldset class="grid_filter_container">
  <legend>Informações</legend>
  <div id="grid_filter">
  	<%= render :partial => "prova_info", :locals => { :duracao => @prova.duracao, :tempo_restante => @prova.get_end_time(params[:estudante_id]), :disponivel_inicio => @prova.disponivel_data_inicio, :disponivel_fim => @prova.disponivel_data_fim } %>
  </div>
</fieldset>

<% if @prova.qtd_falsa_para_anular > 0 %>
<div class="message-block message-warning" style="width: 97%;margin-bottom:20px">
    <div class="message-block-content">
        Atenção: Nesta prova, para cada questão, <%= @prova.qtd_falsa_para_anular %> alternativa(s) errada(s) anula(m) <%= @prova.qtd_verdadeira_anula %> alternativa(s) correta(s).
    </div>
</div>
<% end %>

<a href="#" class="button-primary submit-button-prova" style="margin-right:0px">Finalizar</a>

<fieldset class="prova_container">
	<legend><%= @prova.titulo  %></legend>
	<input type="hidden" name="aluno_id" id="aluno_id" value="<%= params[:estudante_id] %>" />
	<%= form_tag submit_do_test_path(@prova), :class => "form-horizontal", :id => "do_form" do %>
		<input type="hidden" name="disciplina" value="<%= params[:disciplina] %>" />
		<input type="hidden" name="estudante_id" value="<%= params[:estudante_id] %>" />
		<input type="hidden" name="prova_id" value="<%= params[:id] %>" />
		<% @prova.questaos.each_with_index do |questao, i| %>
			<div class="questao" id="questao<%= i + 1 %>">
				<span class="questao_enunciado">
					<strong><%= i + 1 %>) (<%= questao.valor %>)</strong> <%= questao.enunciado %>
				</span>
				<div class="questao_count">
					<hr />
					<span><%= i + 1 %>/<%= @prova.questaos.count %></span>
				</div>
				<div class="header_proposicoes">
					<strong><span>V</span>F</strong>
				</div>
				<div class="proposicoes">
					<%= render :partial => 'proposicao', :collection => questao.proposicaos %>
				</div>
			</div>
		<% end %>
	<% end %>
</fieldset>
<div id="nav_buttons" style="margin-right: 5px">
	<a href="#" data-next-step="#questao1" class="button-default prev-button-prova">Anterior</a>
	<a href="#" data-next-step="#questao2" class="button-default next-button-prova">Próxima</a>
	<input type="hidden" value="<%= @prova.questaos.count %>" id="questoes_num" />
</div>

app/views/provas/new.html.erb
<% content_for :header do %>
  <%= render "shared/professor_header" %>
<% end %>

<div id="form_steps">
	<nav>
		<ul>
			<li></li>
			<li></li>
			<li></li>
		</ul>
		<ul id="steps_titles">
			<li><a href="#">Geral</a></li>
			<li class="navMeio"><a href="#">Questões</a></li>
			<li><a href="#">Resumo</a></li>
		</ul>
	</nav>
</div>

<fieldset id="form_container">
	<%= render 'form' %>
</fieldset>
<div id="nav_buttons">
	<a href="#" data-next-step="#passo1" class="button-default prev-button">Voltar</a>
	<a href="#" data-next-step="#passo2" class="button-default next-button">Continuar</a>
	<a href="#" class="button-success submit-button">Salvar</a>
</div>

app/views/provas/pre_do.html.erb
<% content_for :header do %>
  <%= render "shared/estudante_header" %>
<% end %>

<fieldset class="grid_filter_container">
  <legend>Informações</legend>
  <div id="grid_filter">
  	<%= render :partial => "prova_info", :locals => { :duracao => @prova.duracao, :tempo_restante => DateTime.now.to_i(), :disponivel_inicio => @prova.disponivel_data_inicio, :disponivel_fim => @prova.disponivel_data_fim } %>
  </div>
</fieldset>

<fieldset class="prova_container">
	<legend><%= @prova.titulo  %></legend>
	<input type="hidden" name="aluno_id" id="aluno_id" value="<%= params[:estudante_id] %>" />
	<%= form_tag do_test_path(@prova, :estudante_id => params[:estudante_id], :disciplina => params[:disciplina]), :class => "form-horizontal pre_do_form" do %>
		<input type="submit" name="iniciar" class="button-success button-big" value="Iniciar" />
	<% end %>
</fieldset>