config/routes.rb
QuestoesVf::Application.routes.draw do
  resources :comentarios, :only => [:new, :create, :destroy]
  
  root :to => 'home#index', :as => 'inicial'

  resources :provas, :except => [:index] 
  match 'provas/:id/pre_do' => 'provas#pre_do', :via => :get, :as => 'pre_do_test' ## |
  match 'provas/:id/do/:estudante_id' => 'provas#index', :via => [:post, :get], :as => 'do_test'         ## | INICIAR PROVA -> FAZER PROVA -> ENVIAR PROVA
  match 'provas/:id/do' => 'provas#do', :via => :post, :as => 'submit_do_test'                   ## |

  match 'estudantes/:estudante_id' => 'estudantes#index', :as => 'index_estudantes'

  match 'professores/:professor_id' => 'professors#index', :as => 'index_professores'

  match 'relatorios' => 'relatorios#index', :via => :get
  match 'relatorios' => 'relatorios#report', :via => :post, :as => 'report'
  match 'relatorios/texto' => 'relatorios#texto', :via => :post
  match 'relatorios/excel' => 'relatorios#excel', :via => :post

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/:provider', :to => 'sessions#create', as: :create_session

end

app/controllers/relatorios_controller.rb
class RelatoriosController < ApplicationController
  def index
  	@provas = Prova.do_professor_disciplina(params[:professor_id], params[:disciplina])
  end

  def report
    client = client(params[:disciplina])

    @prova = Prova.find(params[:prova][:id])

    tempos = tempos(@prova.id)

    @num_matriculados = client.members_count
    @num_fizeram_prova = num_fizeram_prova(@prova.id, params[:disciplina])
    @media = @prova.get_media(@prova.disciplina_id)
    @tempo_medio = tempos[0]
    @tempo_max = tempos[1]
    @tempo_min = tempos[2]

    if params[:report] == 'Textual'
      render "texto", :layout => "report"
  	elsif params[:report] == 'Excel'
  			
  	end
  end

  def excel
  end

  private

  def num_fizeram_prova(prova_id, disciplina_id)
    return AlunosProvas.where('provas_id = ? and data_fim is not null', prova_id).count
  end

  def tempos(prova_id)
    media = nil
    max = nil
    min = nil

    total = 0

    alunos_provas = AlunosProvas.where('provas_id = ? and data_fim is not null', prova_id)

    alunos_provas.each { |alunos_prova|
      valor = ((alunos_prova.data_fim - alunos_prova.data_inicio).to_i() / 60)
      total = total + valor

      media = total

      if max == nil
        max = valor
      else
        max = valor > max ? valor : max
      end

      if min == nil
        min = valor
      else
        min = valor < min ? valor : min
      end
    }

    if media != nil
      media = media / alunos_provas.count
    end

    return [media, max, min]
  end

end

app/helpers/relatorio_helper.rb
module RelatorioHelper
end

app/views/relatorios/index.html.erb
<% content_for :header do %>
  <%= render "shared/professor_header" %>
<% end %>

<fieldset id="form_container">
	<div class="relatorio_select">
		<% if @provas.count != 0 %>
		<%= form_tag report_path, :target => "_blank" do %>
			<input type="hidden" name="disciplina" value="<%= params[:disciplina] %>" />
			<input type="hidden" name="professor_id" value="<%= params[:professor_id] %>" />
			<div class="control-group control-inline">
				<div class="control-label">
				    <label for="prova_id">Prova</label>
			  	</div>
			  	<div class="controls">
				    <%= collection_select(:prova, :id, @provas, :id, :titulo) %>
				</div>
				<div class="controls">
				    <input type="submit" value="Textual" name="report" class="button-default" />
				    <input type="submit" value="Excel" name="report" class="button-default" />
				</div>
			</div>
		<% end %>
		<% else %>
		<div class="message-block message-warning" style="width: 325px">
		    <div class="message-block-content" style="padding-right: 0px">
		        Não existem provas cadastradas para a disciplina atual.
		    </div>
		</div>
		<% end %>
	</div>
</fieldset>

app/views/relatorios/texto.html.erb
<fieldset>
	<span class="tempo_prova">
		<span class="tempo_total" style="margin-top:13px;display:block">
			<strong>Tempo total disponível:</strong>
			<%= @prova.duracao %> mim
		</span>
	</span>
	<span class="data_prova">
		<strong>Data início:</strong> <%= @prova.disponivel_data_inicio.strftime('%d/%m/%Y %H:%M') %><br />
		<strong>Data fim:</strong> <%= @prova.disponivel_data_fim.strftime('%d/%m/%Y %H:%M') %>
	</span>
</fieldset>

<br />

<p>
	<span><strong>Número de estudantes matriculados: </strong><%= @num_matriculados %></span><br />
	<span><strong>Número de estudantes que fizeram a prova: </strong><%= @num_fizeram_prova %></span><br />
</p>
<span><strong>Média das notas: </strong><%= @media ||= "?" %> (calculada apenas se a disponibilidade encerrou)</span><br />
<p>
	<span><strong>Tempo médio de duração das provas: </strong><%= @tempo_medio && @tempo_medio >= 0 ? (@tempo_medio == 0 ? "menos de 1 minuto" : @tempo_medio.to_s() + " mim") : "?" %></span><br />
	<span><strong>Tempo mínimo de duração das provas: </strong><%= @tempo_min && @tempo_min >= 0 ? (@tempo_min == 0 ? "menos de 1 minuto" : @tempo_min.to_s() + " mim") : "?" %></span><br />
	<span><strong>Tempo máximo de duração das provas: </strong><%= @tempo_max && @tempo_max >= 0 ? (@tempo_max == 0 ? "menos de 1 minuto" : @tempo_max.to_s() + " mim") : "?" %></span><br />
</p>