config/routes.rb
QuestoesVf::Application.routes.draw do
  resources :comentarios, :only => [:new, :create, :destroy]
  
  root :to => 'home#index', :as => 'inicial'

  resources :provas, :except => [:index] 
  match 'provas/:id/pre_do' => 'provas#pre_do', :via => :get, :as => 'pre_do_test' ## |
  match 'provas/:id/do/:estudante_id' => 'provas#index', :via => [:post, :get], :as => 'do_test'         ## | INICIAR PROVA -> FAZER PROVA -> ENVIAR PROVA
  match 'provas/:id/do' => 'provas#do', :via => :post, :as => 'submit_do_test'                   ## |

  match 'estudantes/:estudante_id' => 'estudantes#index', :as => 'index_estudantes'

  match 'professores/:professor_id' => 'professors#index', :as => 'index_professores'

  match 'relatorios' => 'relatorios#index', :via => :get
  match 'relatorios' => 'relatorios#report', :via => :post, :as => 'report'
  match 'relatorios/texto' => 'relatorios#texto', :via => :post
  match 'relatorios/excel' => 'relatorios#excel', :via => :post

  match '/auth/:provider/callback', :to => 'sessions#create'
  match '/auth/:provider', :to => 'sessions#create', as: :create_session

end

app/views/shared/_empty_grid.html.erb
<div class="message-block message-info">
    <div class="message-block-content">
        Não existem registros para exibir.
    </div>
</div>

app/views/shared/_estudante_header.html.erb
<span class="logo">
	<%= link_to  "Questões V ou F - Estudante", index_estudantes_path(params[:estudante_id], { :disciplina => params[:disciplina] }), :class => "logo_estudante" %>
</span>
<nav class="menu"></nav>

app/views/shared/_filter.html.erb
<fieldset class="grid_filter_container">
  <legend>Filtros</legend>
  <div id="grid_filter">
    <%= form_tag("", :method => "get") do %>
      <span>Excluir Provas:</span>
      <%= check_box_tag(:antigas, 1, params[:antigas] == "1" ? true : false) %>
      <%= label_tag(:antigas, "Antigas") %>
      <%= check_box_tag(:resolvidas, 1, params[:resolvidas] == "1" ? true : false) %>
      <%= label_tag(:resolvidas, "Resolvidas") %>
      <input type="hidden" value="<%= params[:disciplina]%>" name="disciplina" />
    <% end %>
  </div>
</fieldset>

app/views/shared/_grid.html.erb
<%= grid(@provas_grid, show_filters: :no, allow_showing_all_records:  false) do |g|

  g.blank_slate partial: "shared/empty_grid"

  g.column name: 'Título', attribute: 'titulo' do |prova|
    [prova.is_avaliable() || prova.get_data_inicio(params[:estudante_id]) != nil || prova.times_over(params[:estudante_id]) ? link_to(prova.titulo, pre_do_test_path(prova, :estudante_id => params[:estudante_id], :disciplina => params[:disciplina])) : prova.titulo, {style: 'width: 50%;'}]
  end

  g.column name: 'Disponibilidade', attribute: 'disponivel_data_inicio'  do |prova|
    [content_tag(:p , content_tag(:strong, "Início: ") + prova.disponivel_data_inicio.strftime('%d/%m/%Y %H:%M')) +
    content_tag(:strong, "Fim: ") + prova.disponivel_data_fim.strftime('%d/%m/%Y %H:%M'),
    {style: 'width: 25%;'}]
  end  

  g.column name: 'Duração', attribute: 'duracao' do |prova|
    [prova.duracao.to_s() + " mim", {style: 'width: 15%;'}]
  end

  g.column name: 'Nota' do |prova|
    [prova.get_nota(params[:estudante_id], params[:disciplina]) == nil ? "?" : number_with_precision(prova.get_nota(params[:estudante_id], params[:disciplina]), :precision => 2), {style: 'width: 10%;'}]
  end
end -%>

app/views/shared/_grid_professor.html.erb
<%= grid(@provas_grid, show_filters: :no, allow_showing_all_records:  false) do |g|

  g.blank_slate partial: "shared/empty_grid"

  g.column name: 'Título', attribute: 'titulo' do |prova|
    [prova.titulo, {style: 'width: 50%;'}]
  end

  g.column name: 'Disponibilidade', attribute: 'disponivel_data_inicio'  do |prova|
    [content_tag(:p , content_tag(:strong, "Início: ") + prova.disponivel_data_inicio.strftime('%d/%m/%Y %H:%M')) +
    content_tag(:strong, "Fim: ") + prova.disponivel_data_fim.strftime('%d/%m/%Y %H:%M'),
    {style: 'width: 25%;'}]
  end  

  g.column name: 'Duração', attribute: 'duracao' do |prova|
    [prova.duracao.to_s() + " mim", {style: 'width: 15%;'}]
  end

  g.column name: 'Média' do |prova|
    [prova.get_media(params[:disciplina]) == nil ? "?" : number_with_precision(prova.get_media(params[:disciplina]), :precision => 2), {style: 'width: 10%;'}]
  end

  g.column do |prova|
    prova.is_editable() ? link_to('Editar', edit_prova_path(prova, {:disciplina => params[:disciplina], :professor_id => params[:professor_id]})) : ""
  end
end -%>

app/views/shared/_header.html.erb
<span class="logo">
	<%= link_to  "Questões V ou F - Estudante", "#", :class => "logo" %>
</span>
<nav class="menu"></nav>

app/views/shared/_professor_header.html.erb
<span class="logo">
	<%= link_to  "Questões V ou F - Estudante", index_professores_path(params[:professor_id], { :disciplina => params[:disciplina] }), :class => "logo_professor" %>
</span>
<nav class="menu">
	<%= link_to 'Nova Prova', new_prova_path(:disciplina => params[:disciplina], :professor_id => params[:professor_id]), :class => "button-success button-big" %>
	<%= link_to 'Relatórios', relatorios_path(:disciplina => params[:disciplina], :professor_id => params[:professor_id]), :class => "button-default button-big" %>
</nav>

app/views/shared/error_permission.html.erb
<% content_for :header do %>
  <%= render "shared/estudante_header" %>
<% end %>

<fieldset style="width:675px">
	<legend>Error</legend>
	<div class="message-block message-warning" style="width: 97%">
	    <div class="message-block-content">
	        Você não tem permissão para visualizar essa página.
	    </div>
	</div>
</fieldset>